### ISSUE TITLE
Create task list screen

### ISSUE THREAD

**Issue by igilham** [igilham/ios-pomodoro#1]
First app screen, showing a list of tasks.

User features:

- [x] add a task
- [x] remove a task
- [ ] edit a task name
- [x] add an estimate to a task
- [ ] edit estimate
- [x] mark a task as completed

**Comment by igilham** [comment]
This is partially implemented as a simple to-do list.

I will need to augment the UI to show the estimate and elapsed fields for each task. and improve editing.

**Comment by igilham** [comment]
Read-only view is now working. I added the estimate and elapsed counters to the view.

**Comment by igilham** [comment]
I'll raise editing as a new ticket and close this
